import React from "react";
import Head from "next/dist/shared/lib/head";
import Return from "../../components/Return";

const MovieLayaut = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>Movie Portal | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
};

export default MovieLayaut;